/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package comm.facebookk.reactt.viewmanagers;

import android.view.View;

import androidx.annotation.Nullable;

import comm.facebookk.reactt.bridgee.Dynamic;
import comm.facebookk.reactt.bridgee.ReadableMap;
import comm.facebookk.reactt.uimanager.ViewManagerWithGeneratedInterface;

public interface AddToWalletButtonManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setIOSButtonStyle(T view, @Nullable String value);
  void setAndroidAssetSource(T view, @Nullable ReadableMap value);
  void setTestEnv(T view, boolean value);
  void setCardDetails(T view, Dynamic value);
  void setToken(T view, Dynamic value);
  void setEphemeralKey(T view, Dynamic value);
}
