/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package comm.facebookk.reactt.viewmanagers;

import android.view.View;

import comm.facebookk.reactt.bridgee.Dynamic;
import comm.facebookk.reactt.uimanager.ViewManagerWithGeneratedInterface;

public interface EmbeddedPaymentElementViewManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setConfiguration(T view, Dynamic value);
  void setIntentConfiguration(T view, Dynamic value);
  void confirm(T view);
  void clearPaymentOption(T view);
}
